import type { HighSchoolTrack, Subject } from "../types";



export interface TrackSubjects {
  [key: string]: any[];
}

export interface YearSubjects {
  [key: string]: any;
}

export const subjectsByTrack: any = {
   first: {
     Semester_1: [
       { en: "Math", ar: "الرياضيات" },
       { en: "English", ar: "اللغة الإنجليزية" },
       { en: "The Holy Quran and Interpretation", ar: "القرآن الكريم وتفسيره" },
       { en: "Arabic Language", ar: "كفايات لغوية" },
       { en: "Biology", ar: "علم الأحياء" },
       { en: "Digital Technology", ar: "التقنية الرقمية" },        
     ],
     Semester_2: [
       { en: "Math", ar: "الرياضيات" },
       { en: "English", ar: "اللغة الإنجليزية" },
       { en: "Vocational Education", ar: "التعليم المهني" },
       { en: "Arabic Language", ar: "كفايات لغوية" },
       { en: "Physics", ar: "الفيزياء" },
       { en: "Digital Technology", ar: "التقنية الرقمية" },
       { en: "PE", ar: "التربية البدنية" },
     ],
     Semester_3: [
       { en: "Math", ar: "الرياضيات" },
       { en: "English", ar: "اللغة الإنجليزية" },
       { en: "Chemistry", ar: "الكيمياء" },
       { en: "Digital Technology", ar: "التقنية الرقمية" },
       { en: "Hadith", ar: "الحديث" },
       { en: "Financial Knowledge", ar: "المعرفة المالية" },
       { en: "PE", ar: "التربية البدنية" },
       { en: "Social Studies and History", ar: "الدراسات الاجتماعية والتاريخ" },
     ],
   },
   second: {
     general: {
       Semester_1: [
         { en: "Math", ar: "الرياضيات" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Arts", ar: "الفنون" },
         { en: "PE", ar: "التربية البدنية" },
       ],
       Semester_2: [
         { en: "Math", ar: "الرياضيات" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "History", ar: "التاريخ" },
       ],
       Semester_3: [
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Math", ar: "الرياضيات" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "Physics", ar: "الفيزياء" },
       ],
     },
 
     cs: {
       Semester_1: [
         { en: "Math", ar: "الرياضيات" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Engineering", ar: "الهندسة" },
         { en: "Data Science", ar: "علم البيانات" },
       ],
       Semester_2: [
         { en: "Math", ar: "الرياضيات" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "IoT", ar: "إنترنت الأشياء" },
         { en: "PE", ar: "التربية البدنية" },
       ],
       Semester_3: [
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Math", ar: "الرياضيات" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "IoT", ar: "إنترنت الأشياء" },
         { en: "Physics", ar: "الفيزياء" },
       ],
     },
     health: {
       Semester_1: [
         { en: "Math", ar: "الرياضيات" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Arts", ar: "الفنون" },
         { en: "PE", ar: "التربية البدنية" },
       ],
       Semester_2: [
         { en: "Math", ar: "الرياضيات" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "Fundamentals of Health Science", ar: "أساسيات العلوم الصحية" },
       ],
       Semester_3: [
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Chemistry", ar: "الكيمياء" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Math", ar: "الرياضيات" },
         { en: "Biology", ar: "علم الأحياء" },
         { en: "Fundamentals of Health Science", ar: "أساسيات العلوم الصحية" },
         { en: "Physics", ar: "الفيزياء" },
       ],
     },
 
     business: {
       Semester_1: [
         { en: "Quran Interpretation", ar: "تفسير القرآن" },
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Making Decisions in Business", ar: "اتخاذ القرارات في الأعمال" },
         { en: "Starting in Business", ar: "البدء في الأعمال" },
         { en: "Financial Management", ar: "إدارة المالية" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "PE", ar: "التربية البدنية" },
       ],
       Semester_2: [
         { en: "History", ar: "التاريخ" },
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Making Decisions in Business", ar: "اتخاذ القرارات في الأعمال" },
         { en: "Starting in Business", ar: "البدء في الأعمال" },
         { en: "Financial Management", ar: "إدارة المالية" },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "English", ar: "اللغة الإنجليزية" },
       ],
       Semester_3: [
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Linguistic Studies", ar: "الدراسات اللغوية" },
         { en: "Making Decisions in Business", ar: "اتخاذ القرارات في الأعمال" },
         { en: "Fundamentals of Management", ar: "أساسيات الإدارة" },
         { en: "Arts", ar: "الفنون" },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "English", ar: "اللغة الإنجليزية" },
       ],
     },
 
     shariah: {
       Semester_1: [
         { en: "Hadith", ar: "الحديث" },
         { en: "Holy Quran", ar: "القرآن الكريم" },
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Elective", ar: "اختياري", elective: true },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "PE", ar: "التربية البدنية" },
       ],
       Semester_2: [
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Holy Quran", ar: "القرآن الكريم" },
         { en: "Elective", ar: "اختياري", elective: true },
         { en: "Arabic Language", ar: "كفايات لغوية" },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "History", ar: "التاريخ" },
         { en: "English", ar: "اللغة الإنجليزية" },
       ],
       Semester_3: [
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Holy Quran", ar: "القرآن الكريم" },
         { en: "Quranic Studies", ar: "علوم القرآن" },
         { en: "Linguistic Studies", ar: "الدراسات اللغوية" },
         { en: "Quran Interpretation", ar: "تفسير القرآن" },
         { en: "Arts", ar: "الفنون" },
         { en: "English", ar: "اللغة الإنجليزية" },
       ],
     },
   },
 
   third: {
     general: {
       Semester_1: [
         { en: "Chemistry", ar: "الكيمياء" },
         {
           en: "Research and Information Sources",
           ar: "البحث ومصادر المعلومات",
         },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Mathematics", ar: "الرياضيات" },
         { en: "Physics", ar: "الفيزياء" },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "Elective", ar: "اختياري", elective: true },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_2: [
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Life Skills", ar: "مهارات الحياة" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Mathematics", ar: "الرياضيات" },
         { en: "Physics", ar: "الفيزياء" },
         { en: "Digital Citizenship", ar: "المواطنة الرقمية" },
         { en: "Earth and Space Sciences", ar: "علوم الأرض والفضاء" },
         { en: "Elective", ar: "اختياري", elective: true },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_3: [
         { en: "Literary Studies", ar: "الدراسات الأدبية" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Mathematics", ar: "الرياضيات" },
         { en: "Physics", ar: "الفيزياء" },
         {
           en: "Psychological and Social Studies",
           ar: "الدراسات النفسية والاجتماعية",
         },
         { en: "Earth and Space Sciences", ar: "علوم الأرض والفضاء" },
         { en: "Elective", ar: "اختياري", elective: true },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
     },
     cs: {
       Semester_1: [
         { en: "Software Engineering", ar: "هندسة البرمجيات" },
         {
           en: "Research and Information Sources",
           ar: "البحث ومصادر المعلومات",
         },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Mathematics", ar: "الرياضيات" },
         { en: "Physics", ar: "الفيزياء" },
         { en: "AI", ar: "الذكاء الاصطناعي" },
         { en: "Chemistry 3", ar: "الكيمياء 3" },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_2: [
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Earth and Space Sciences", ar: "علوم الأرض والفضاء" },
         { en: "English (2-3)", ar: "اللغة الإنجليزية (2-3)" },
         { en: "Mathematics (2-3)", ar: "الرياضيات (2-3)" },
         { en: "Physics (2-3)", ar: "الفيزياء (2-3)" },
         { en: "AI", ar: "الذكاء الاصطناعي" },
         { en: "Engineering Design", ar: "تصميم هندسي" },
         { en: "Life Skills", ar: "مهارات الحياة" },
       ],
       Semester_3: [
         { en: "Project Graduation", ar: "مشروع التخرج" },
         { en: "Earth and Space Sciences", ar: "علوم الأرض والفضاء" },
         { en: "English (3-3)", ar: "اللغة الإنجليزية (3-3)" },
         { en: "Mathematics (3-3)", ar: "الرياضيات (3-3)" },
         { en: "Physics (3-3)", ar: "الفيزياء (3-3)" },
         { en: "Cybersecurity", ar: "الأمن السيبراني" },
         { en: "Literary Studies", ar: "الدراسات الأدبية" },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
     },
     health: {
       Semester_1: [
         {
           en: "Research and Information Sources",
           ar: "البحث ومصادر المعلومات",
         },
         { en: "English (1-3)", ar: "اللغة الإنجليزية (1-3)" },
         { en: "Mathematics (1-3)", ar: "الرياضيات (1-3)" },
         { en: "Physics (1-3)", ar: "الفيزياء (1-3)" },
         { en: "Health Sciences (Innovation)", ar: "الأبتكار في العلوم الصحية" },
         { en: "Human Body Systems", ar: "أنظمة الجسم البشري" },
         { en: "Chemistry (3)", ar: "الكيمياء (3)" },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_2: [
         { en: "Tawhid", ar: "التوحيد" },
         { en: "English (2-3)", ar: "اللغة الإنجليزية (2-3)" },
         { en: "Mathematics (2-3)", ar: "الرياضيات (2-3)" },
         { en: "Physics (2-3)", ar: "الفيزياء (2-3)" },
         { en: "Health Sciences (Innovation)", ar: "الأبتكار في العلوم الصحية" },
         { en: "Earth and Space Sciences", ar: "علوم الأرض والفضاء" },
         { en: "Engineering Design", ar: "تصميم هندسي" },
         { en: "Life Skills", ar: "مهارات الحياة" },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_3: [
         { en: "Literary Studies", ar: "الدراسات الأدبية" },
         { en: "English (3-3)", ar: "اللغة الإنجليزية (3-3)" },
         { en: "Mathematics (3-3)", ar: "الرياضيات (3-3)" },
         { en: "Physics (3-3)", ar: "الفيزياء (3-3)" },
         {
           en: "Statistics (Applications in Health)",
           ar: "الإحصاء (تطبيقات في الصحة)",
         },
         { en: "Earth and Space Sciences", ar: "علوم الأرض والفضاء" },
         { en: "Project Graduation", ar: "مشروع التخرج" },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
     },
     business: {
       Semester_1: [
         { en: "Literary Studies", ar: "الدراسات الأدبية" },
         {
           en: "Statistics (Applications in Business)",
           ar: "الإحصاء (تطبيقات في الأعمال)",
         },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Principles of Law", ar: "مبادئ القانون" },
         {
           en: "Research and Information Sources",
           ar: "البحث ومصادر المعلومات",
         },
         { en: "Entrepreneurship", ar: "ريادة الأعمال" },
         { en: "Geography", ar: "الجغرافيا" },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_2: [
         {
           en: "Secretarial and Office Management",
           ar: "إدارة المكاتب والأمانة",
         },
         { en: "Principles of Accounting (1-1)", ar: "مبادئ المحاسبة (1-1)" },
         { en: "English (2-3)", ar: "اللغة الإنجليزية (2-3)" },
         { en: "Digital Citizenship", ar: "المواطنة الرقمية" },
         { en: "Principles of Law (2-1)", ar: "مبادئ القانون (2-1)" },
         { en: "Life Skills", ar: "مهارات الحياة" },
         { en: "Entrepreneurship (2-2)", ar: "ريادة الأعمال (2-2)" },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_3: [
         {
           en: "Arabic Language - Critical Rhetoric",
           ar: "اللغة العربية - البلاغة النقدية",
         },
         { en: "Principles of Accounting (2-1)", ar: "مبادئ المحاسبة (2-1)" },
         { en: "English (3-3)", ar: "اللغة الإنجليزية (3-3)" },
         { en: "Applications in Law", ar: "تطبيقات في القانون" },
         {
           en: "Psychological and Social Studies",
           ar: "الدراسات النفسية والاجتماعية",
         },
         { en: "Project Graduation", ar: "مشروع التخرج" },
         {
           en: "Applications in Entrepreneurship",
           ar: "تطبيقات في ريادة الأعمال",
         },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
     },
     shariah: {
       Semester_1: [
         { en: "Chemistry", ar: "الكيمياء" },
         {
           en: "Research and Information Sources",
           ar: "البحث ومصادر المعلومات",
         },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Mathematics", ar: "الرياضيات" },
         { en: "Physics", ar: "الفيزياء" },
         { en: "Digital Technology", ar: "التقنية الرقمية" },
         { en: "Elective", ar: "اختياري", elective: true },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_2: [
         { en: "Tawhid", ar: "التوحيد" },
         { en: "Life Skills", ar: "مهارات الحياة" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Mathematics", ar: "الرياضيات" },
         { en: "Physics", ar: "الفيزياء" },
         { en: "Digital Citizenship", ar: "المواطنة الرقمية" },
         { en: "Earth and Space Sciences", ar: "علوم الأرض والفضاء" },
         { en: "Elective", ar: "اختياري", elective: true },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
       Semester_3: [
         { en: "Literary Studies", ar: "الدراسات الأدبية" },
         { en: "English", ar: "اللغة الإنجليزية" },
         { en: "Mathematics", ar: "الرياضيات" },
         { en: "Physics", ar: "الفيزياء" },
         {
           en: "Psychological and Social Studies",
           ar: "الدراسات النفسية والاجتماعية",
         },
         { en: "Earth and Space Sciences", ar: "علوم الأرض والفضاء" },
         { en: "Elective", ar: "اختياري", elective: true },
         { en: "Itqan", ar: "حصص إتقان" },
       ],
     },
   },
 };
 